version: "3.9"
services:
  frontend:
    build: 
      context: frontend
      args:
        MOCKED_VALUES: "false"
    ports:
      - "8080:8080"
  db:
    image: postgres:12.11-alpine
    restart: always
    env_file: backend/.env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes: 
      - db:/var/lib/postgresql/data
  backend:
    build: 
      context: backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    links:
      - db
    env_file: backend/.env
    environment:
      PGHOST: '${POSTGRES_HOST}'
      PGDATABASE: '${POSTGRES_DATABASE}'
      PGUSER: '${POSTGRES_USER}'
      PGPASSWORD: '${POSTGRES_PASSWORD}'
volumes:
  db:
    driver: local
