"""empty message

Revision ID: 969e2af8c41d
Revises: bb1c7dfd4bd9
Create Date: 2022-04-25 21:24:32.295157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969e2af8c41d'
down_revision = 'bb1c7dfd4bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage-stamps', 'current_month_download',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('usage-stamps', 'current_month_upload',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage-stamps', 'current_month_upload',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('usage-stamps', 'current_month_download',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
