const MOCKED_MONTH_DOWNLOAD = 87.559
const MOCKED_MONTH_UPLOAD = 3.553
const MOCKED_TIME_STAMP =  "Sun, 26 Jun 2022 17:56:48 GMT"

const USAGE_STAMP_API_ENDPOINT = "http://localhost:5005/api/usage-stamp"

export { MOCKED_MONTH_DOWNLOAD, MOCKED_MONTH_UPLOAD, MOCKED_TIME_STAMP, USAGE_STAMP_API_ENDPOINT }